server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


zuul:
  routes:
    department:
      path: /department/**
      serviceId: demo-department-service
    employee:
      path: /employee/**
      serviceId: demo-employee-service
    organization:
      path: /organization/**
      serviceId: demo-organization-service



hystrix:
  command:
    service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    circuitBreaker:
      requestVolumeThreshold: 3
      errorThresholdPercentage: 50



