server:
  port: 8082

spring:
  profiles:
    active: dev
        
  data:
        mongodb:
            uri: mongodb://localhost:27017
            database: emv_ms_users
            
app:
  info: application-dev.yml            