server:
  port: 8082

spring:
  profiles:
    active: local
    include: swagger

  data:
        mongodb:
            uri: mongodb://localhost:27017
            database: emv_ms_users
            
app:
  info: application-local.yml             